#!/usr/bin/env bash
# Provision one isolated Supabase-lite stack for a hackathon team.
#
# Usage: ./scripts/deploy-team.sh <team-slug> <team-number>
#   team-slug:   lowercase alphanumeric + hyphens (e.g. "alpha")
#   team-number: integer 1..99 — drives port offsets (8000+N, 8400+N, 5430+N)
#
# Idempotent: rerunning against the same slug tears down and rebuilds.
# After success, handouts/team-<slug>.txt contains the team's credentials.

source "$(dirname "$0")/_lib.sh"

[[ $# -eq 2 ]] || die "usage: $0 <team-slug> <team-number>"

SLUG="$1"
TEAM_NUM="$2"

validate_slug "$SLUG"
validate_team_number "$TEAM_NUM"

require_cmd docker
require_cmd openssl

API_PORT=$((8000 + TEAM_NUM))
STUDIO_PORT=$((8400 + TEAM_NUM))
POSTGRES_PORT=$((5430 + TEAM_NUM))

ENV_FILE="$(team_env_file "$SLUG")"
HANDOUT_FILE="$REPO_ROOT/handouts/team-${SLUG}.txt"

# ----------------------------------------------------------------------
# 1. Tear down any existing stack for this slug (idempotency)
# ----------------------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
  log "tearing down existing stack for team=$SLUG"
  team_compose "$SLUG" down -v --remove-orphans || true
fi

# ----------------------------------------------------------------------
# 2. Generate credentials
# ----------------------------------------------------------------------
log "generating credentials for team=$SLUG"
JWT_SECRET="$(rand_secret)"
POSTGRES_PASSWORD="$(rand_secret)"
AUTHENTICATOR_PASSWORD="$(rand_secret)"
TEAM_DB_PASSWORD="$(rand_secret)"
TEAM_DB_USER="team_writer_${SLUG//-/_}"
STUDIO_DASHBOARD_USERNAME="team_${SLUG}"
STUDIO_DASHBOARD_PASSWORD="$(rand_secret)"

## JWT role -> DB role mapping used by PostgREST (SET ROLE on each request).
## Using team_writer (not anon) so unauth callers + invalid-signature tokens
## fall back to anon which has no data access. This is the team-isolation wall.
ANON_KEY="$(make_jwt "$JWT_SECRET" team_writer)"
SERVICE_ROLE_KEY="$(make_jwt "$JWT_SECRET" team_writer)"

# ----------------------------------------------------------------------
# 3. Write env file
# ----------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy-team.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Team: $SLUG (#$TEAM_NUM)
TEAM_SLUG=$SLUG
API_PORT=$API_PORT
STUDIO_PORT=$STUDIO_PORT
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_DB=hackathon
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
AUTHENTICATOR_PASSWORD=$AUTHENTICATOR_PASSWORD
TEAM_DB_USER=$TEAM_DB_USER
TEAM_DB_PASSWORD=$TEAM_DB_PASSWORD
STUDIO_DASHBOARD_USERNAME=$STUDIO_DASHBOARD_USERNAME
STUDIO_DASHBOARD_PASSWORD=$STUDIO_DASHBOARD_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
EOF
chmod 600 "$ENV_FILE"
log "wrote $ENV_FILE"

# ----------------------------------------------------------------------
# 4. Bring up the stack
# ----------------------------------------------------------------------
log "starting docker stack for team=$SLUG (api=$API_PORT studio=$STUDIO_PORT db=$POSTGRES_PORT)"
team_compose "$SLUG" up -d

wait_for_db "$SLUG"

# ----------------------------------------------------------------------
# 5. Apply migrations
# ----------------------------------------------------------------------
log "applying migrations"
for migration in "$REPO_ROOT"/supabase/migrations/*.sql; do
  log "  $(basename "$migration")"
  team_compose "$SLUG" exec -T db \
    psql -U postgres -d hackathon -v ON_ERROR_STOP=1 < "$migration"
done

# ----------------------------------------------------------------------
# 6. Set authenticator password + create team DB user
#    (Done after migrations because roles are created there.)
# ----------------------------------------------------------------------
log "setting authenticator password + creating team user $TEAM_DB_USER"
team_psql "$SLUG" <<EOF
ALTER ROLE authenticator WITH PASSWORD '$AUTHENTICATOR_PASSWORD';
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$TEAM_DB_USER') THEN
    CREATE USER $TEAM_DB_USER WITH LOGIN PASSWORD '$TEAM_DB_PASSWORD';
  ELSE
    ALTER USER $TEAM_DB_USER WITH PASSWORD '$TEAM_DB_PASSWORD';
  END IF;
END \$\$;
GRANT team_writer TO $TEAM_DB_USER;
EOF

# ----------------------------------------------------------------------
# 7. Apply seed data if present (optional — generate.py produces this)
# ----------------------------------------------------------------------
SEED_FILE="$REPO_ROOT/supabase/seed.sql"
if [[ -f "$SEED_FILE" ]]; then
  log "loading seed data"
  team_compose "$SLUG" exec -T db \
    psql -U postgres -d hackathon -v ON_ERROR_STOP=1 < "$SEED_FILE"
else
  warn "no seed.sql yet — stack is up but DB is empty"
fi

# ----------------------------------------------------------------------
# 8. Restart PostgREST so it picks up the authenticator password + schema
# ----------------------------------------------------------------------
team_compose "$SLUG" restart postgrest

# ----------------------------------------------------------------------
# 9. Write handout
# ----------------------------------------------------------------------
HOST="${MANEX_HOST:-localhost}"
mkdir -p "$REPO_ROOT/handouts"
cat > "$HANDOUT_FILE" <<EOF
Team $SLUG
===========================================================

REST API:     http://$HOST:$API_PORT/
Studio UI:    http://$HOST:$STUDIO_PORT/
Studio Login: $STUDIO_DASHBOARD_USERNAME / $STUDIO_DASHBOARD_PASSWORD
PostgreSQL:   postgres://$TEAM_DB_USER:$TEAM_DB_PASSWORD@$HOST:$POSTGRES_PORT/hackathon

API Key (Authorization: Bearer header):
$ANON_KEY

Quick start:
  export KEY="$ANON_KEY"
  curl -H "Authorization: Bearer \$KEY" "http://$HOST:$API_PORT/defect?limit=5"

Shared image server: http://$HOST:9000/defect_images/

See docs/QUICKSTART.md for more examples.
EOF
chmod 600 "$HANDOUT_FILE"

# ----------------------------------------------------------------------
# Summary
# ----------------------------------------------------------------------
cat <<EOF

────────────────────────────────────────────────────────────
✓ Team $SLUG deployed (#$TEAM_NUM)
────────────────────────────────────────────────────────────
  REST API:    http://$HOST:$API_PORT/
  Studio UI:   http://$HOST:$STUDIO_PORT/
  Postgres:    postgres://$TEAM_DB_USER:***@$HOST:$POSTGRES_PORT/hackathon
  Handout:     $HANDOUT_FILE
────────────────────────────────────────────────────────────
EOF
