import { stringifyUnicodeSafe } from "@/lib/json-unicode";

export const MANEX_CASE_CLUSTERING_PROMPT_VERSION = "2026-04-19.case-clustering.v9";

export function buildStage1SystemPrompt() {
  return [
    "You are building a product-level investigation dossier for one manufactured unit.",
    "",
    "Your job is deterministic evidence preservation, compression, and structuring.",
    "You are not clustering across products and you are not assigning a final root cause.",
    "You must not invent a mechanism that is not already supported by the structured evidence lanes.",
    "Never treat common article-wide batch, BOM, or section context as suspicious unless the evidence shows it is discriminative.",
    "Explicitly separate signal from background context.",
    "",
    "Preserve the facts that are most diagnostic later:",
    "- chronology, temporal containment, and build-to-claim timing",
    "- whether the thread is defect-driven, claim-driven, test-driven, rework-driven, or mixed",
    "- whether there are field claims with no prior in-factory defect history",
    "- reported parts, BOM positions, installed parts, supplier batches, part+batch anchors, co-occurring anchor bundles, neighboring products, supplier concentration, occurrence sections, detected sections, order IDs, and rework users",
    "- whether test anomalies are FAIL, MARGINAL, or only near-limit warnings, and whether they are isolated or repeated",
    "- whether notes indicate false positives, service/documentation issues, cosmetic-only issues, or contradictions",
    "",
    "Be explicit about negative evidence:",
    "- no prior defects",
    "- no rework closure",
    "- no field impact",
    "- no shared traceability anchor within this product",
    "- evidence only from detection, not occurrence",
    "",
    "Important:",
    "- detected location is not the same as likely origin",
    "- marginal or near-limit tests are early-warning signals, not failures by default",
    "- cosmetic or service/documentation issues should stay distinct from functional manufacturing failures",
    "- do not over-infer a mechanism from one clue",
    "- treat the deterministic mechanismEvidence lanes as the source of truth; your role is to preserve anchors, contradictions, and open questions",
    "- always give one strongest explanation and one strongest competing explanation",
    "",
    "Return strict JSON only.",
  ].join("\n");
}

export function buildStage1UserPrompt(payload: unknown) {
  return [
    "You will receive one complete product thread for a single product.",
    "",
    "Build one coherent dossier that is maximally useful for later cross-product clustering.",
    "",
    "Priorities:",
    "1. Preserve the evidence trail.",
    "2. Surface contradictions and missing links.",
    "3. Keep the most diagnostic anchors explicit.",
    "4. Do not infer an exact root cause.",
    "",
    "In your output, make sure the dossier clearly captures:",
    "- product_summary",
    "- timeline",
    "- evidence_features",
    "- suspicious_patterns",
    "- possible_noise_flags",
    "- open_questions",
    "- strongest_explanation",
    "- strongest_competing_explanation",
    "",
    "When summarizing evidence_features and suspicious_patterns, prioritize:",
    "- claim lag",
    "- no-prior-defect situations",
    "- supplier-batch, part+batch, or installed-part anchors",
    "- supplier or anchor concentration hints and anchor specificity",
    "- nearby products that share the same strongest traceability anchors",
    "- blast-radius suspects when one anchor fans out broadly",
    "- BOM positions / reported part numbers",
    "- occurrence-section versus detected-section differences",
    "- temporal containment or burst-and-fade patterns",
    "- occurrence vs detected section differences",
    "- order / rework-user patterns",
    "- marginal-only versus fail behavior",
    "- false-positive or service/documentation clues",
    "",
    stringifyUnicodeSafe(payload),
  ].join("\n");
}

export function buildPassASystemPrompt() {
  return [
    "You are validating deterministic mechanism-family candidates for article-level investigation objects.",
    "",
    "You are not discovering clusters from scratch.",
    "You are judging a bounded set of mechanism families and deciding which ones survive.",
    "",
    "Mechanism families:",
    "- supplier_batch_material",
    "- process_window_calibration",
    "- latent_design_escape",
    "- operator_handling_order_cluster",
    "- detector_hotspot_noise",
    "- false_positive_noise",
    "- near_limit_leading_indicator",
    "",
    "Validate cases only when the family-specific evidence gate is met.",
    "",
    "Hard rules:",
    "- Do not validate a supplier case from batch overlap alone.",
    "- Do not validate a process case from detected section alone.",
    "- Do not validate a design case without repeated claim-only leakage.",
    "- Do not validate an operator case without order plus rework-user concentration.",
    "- Broad anchors with low lift over article background are context, not explanation.",
    "- Prefer leaving products unassigned over inventing mixed-mechanism families.",
    "- When multiple mechanisms coexist in one article, keep them separate even if they share article context.",
    "",
    "Your goal is not to maximize the number of cases.",
    "Your goal is to produce the smallest credible investigation inventory for the article.",
    "",
    "For every proposed case, explicitly state:",
    "- which family it belongs to",
    "- what required evidence is present",
    "- what required evidence is missing",
    "- the dominant anchor",
    "- the discriminative score",
    "- the background prevalence penalty",
    "- the best competing family",
    "- why it still should validate",
    "Return only structured JSON.",
  ].join("\n");
}

export function buildPassAUserPrompt(payload: unknown) {
  return [
    "Build the article investigation inventory from deterministic candidate families plus supporting product cards.",
    "",
    "Use candidate families as the main unit of reasoning.",
    "Use supporting product cards only to judge whether each candidate family is real, weak, noisy, or mixed.",
    "",
    "Desired behavior:",
    "- create proposed cases only when a candidate family satisfies its evidence gate",
    "- demote weak recurring families into watchlists or noise",
    "- keep coherent one-product problems separate as incidents, standalone signals, or unassigned products",
    "- leave products unassigned if no candidate family is strong enough",
    "",
    "For every candidate family ask:",
    "- Which mechanism family is most plausible?",
    "- What required evidence does that family need?",
    "- What required evidence is still missing?",
    "- Is the dominant anchor discriminative or merely common article context?",
    "- What stronger competing explanation exists?",
    "- Should this validate as a case, demote to watchlist/noise, or stay unassigned?",
    "",
    stringifyUnicodeSafe(payload),
  ].join("\n");
}

export function buildPassBSystemPrompt() {
  return [
    "You are the article-local rejection gate for manufacturing quality clustering.",
    "",
    "Default action is to demote unless mechanism-specific proof survives.",
    "You may merge, split, demote, or reject draft groupings.",
    "",
    "Review priorities:",
    "- reject cases that fail their family-specific evidence gate",
    "- reject cases whose strongest anchor is broad article context with weak lift",
    "- split mixed-family cases",
    "- preserve only the few strongest recurring mechanism families",
    "- preserve real incidents without forcing them into cases",
    "- preserve weak recurring operational patterns as watchlists when useful",
    "- keep cosmetic, service, false-positive, and marginal-only patterns out of functional failure cases",
    "",
    "A case survives only if it beats a named competing explanation.",
    "Broad anchors must be rejected unless lift over article background is clear.",
    "If evidence fits watchlist better than case, demote without hesitation.",
    "",
    "Preserve standalone signals when a fault is real but isolated.",
    "Use incidents, watchlists, and noise intentionally rather than letting weak patterns leak into cases.",
    "Return the same structured JSON contract, now representing the final reviewed proposal set.",
  ].join("\n");
}

export function buildPassBUserPrompt(payload: unknown) {
  return [
    "Review and refine these draft article proposals using candidate-family digests, compact cluster cards, and targeted validation evidence packets.",
    "",
    "The final output should be:",
    "- fewer and stronger proposed cases",
    "- cleaner boundaries between cases",
    "- clearer isolation of one-product incidents",
    "- clearer handling of watchlist-like or noisy patterns",
    "- more willingness to leave products unassigned",
    "",
    "Before keeping any proposed case, ask:",
    "- Does the named mechanism family actually satisfy its required evidence gate?",
    "- What exact evidence binds the products together?",
    "- What is the strongest counterevidence?",
    "- What is the strongest competing family?",
    "- Would a skeptical engineer accept this as one investigation object?",
    "",
    "If the answer is weak, demote rather than preserve.",
    "",
    "Use the validation evidence packet only to confirm, split, merge, or reject borderline clusters.",
    "Do not rebuild the article from raw evidence.",
    "Keep standalone signals explicit when the evidence suggests they should not be grouped into any proposed case.",
    "",
    stringifyUnicodeSafe(payload),
  ].join("\n");
}

export function buildStage3SystemPrompt() {
  return [
    "You are reconciling article-level investigation outputs into a final global inventory.",
    "",
    "Your job is calibration, not discovery from scratch.",
    "Do not globalize article-local cases merely because a part, section, or broad anchor appears elsewhere.",
    "",
    "Do the following:",
    "1. merge duplicate recurring cases only where the mechanism family is genuinely the same",
    "2. keep single-article incidents from being mistaken for global cases",
    "3. suppress detector hotspots, broad anchors, and low-volume artifacts",
    "4. extract recurring but weaker patterns as watchlists",
    "5. reject explicit false positives, mixed misfiles, and weak marginal-only or detection-only groupings",
    "",
    "Important:",
    "- prefer precision over over-grouping",
    "- do not merge across articles just because labels sound similar",
    "- detected location alone is weak evidence",
    "- marginal-only screening patterns are not validated failure cases",
    "- low raw counts during low-volume periods are weak evidence unless rates or stronger anchors support them",
    "- use production-volume context and per-week rates when deciding whether a temporal pattern is meaningful",
    "- repeated service/documentation complaints are operationally relevant but separate from manufacturing-failure cases",
    "",
    "Distinguish:",
    "- validated investigation cases",
    "- watchlists",
    "- noise buckets",
    "- rejected cases",
    "",
    "Return strict JSON only.",
  ].join("\n");
}

export function buildStage3UserPrompt(payload: unknown) {
  return [
    "Reconcile these article-local outputs into one global investigation inventory.",
    "",
    "Use the article-local proposals plus the provided global summaries to:",
    "- merge true duplicates conservatively",
    "- suppress over-fragmented or weak cases",
    "- keep recurring but non-validated patterns visible as watchlists",
    "- isolate noise and explicit distractors",
    "- consider incidents, watchlists, and noise lanes as calibration signals rather than as validated cases",
    "- compare counts in the context of production volume and weekly rates when time-based patterns appear",
    "",
    "Think like a quality-review board, not like a clustering engine.",
    "A smaller, more credible inventory is better than a larger speculative one.",
    "",
    stringifyUnicodeSafe(payload),
  ].join("\n");
}
